### ISSUE TITLE
not working with node version node@v4.1.1 npm@2.14.4

### ISSUE THREAD

**Issue by cristinaperezscmspain** [SUI-Components/generator-sui-react#14]
Failed at the sui-showcase@0.0.0 dist:styles script 'node-sass src/index.scss dist/sui-showcase.css --importer ./scripts/importer.js'.

**Comment by carlosvillu** [comment]
What is sui-showcase@0.0.0 ?!

**Comment by cristinaperezscmspain** [comment]
component's name I wrote when the generator asks you to name it

**Comment by danderu** [comment]
@cristinaperezscmspain can you try to upgrade to v3.0.0?

**Comment by danderu** [comment]
@cristinaperezscmspain is this still an issue?

**Comment by danderu** [comment]
I'm closing this issue, since we haven't been able to reproduce it
